apiVersion: v1
kind: Pod
metadata:
  name: two-containers-pod
spec:
  containers:
  - name: container1
    image: busybox
    command: ["/bin/sh", "-c", "echo hello; sleep 3600"]
  - name: container2
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
